### ISSUE TITLE
can it work on s10 plus?

### ISSUE THREAD

**Issue by qasimkhn** [ravindu644/android_kernel_beyondx_lpos#1]
dont u have nethunter kernel for s10 plus?

**Comment by ravindu644** [comment]
> dont u have nethunter kernel for s10 plus?

I have a s10+ version.

**Comment by qasimkhn** [comment]
> > dont u have nethunter kernel for s10 plus?
> 
> I have a s10+ version.

i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me  nethunter kernel for s10 plus so it can work with all nethunter feature

**Comment by ravindu644** [comment]
> > > dont u have nethunter kernel for s10 plus?
> > 
> > 
> > I have a s10+ version.
> 
> i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature

Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.

I left the development, so I won't make any kernels :(

**Comment by qasimkhn** [comment]
> > > > dont u have nethunter kernel for s10 plus?
> > > 
> > > 
> > > I have a s10+ version.
> > 
> > 
> > i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature
> 
> Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.
> 
> I left the development, so I won't make any kernels :(

thanks alot brother,,, i am that good in it brother just still learning,,,any video tutorial u suggest please?and on samsung s10 plus my nethunter is working well no problems,,,only problem is that to use bluetooth and wifi on it ?if u can help me with this i will be realy happy

**Comment by ravindu644** [comment]
> > > > > dont u have nethunter kernel for s10 plus?
> > > > 
> > > > 
> > > > I have a s10+ version.
> > > 
> > > 
> > > i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature
> > 
> > Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.
> > 
> > I left the development, so I won't make any kernels :(
> 
> thanks alot brother,,, i am that good in it brother just still learning,,,any video tutorial u suggest please?and on samsung s10 plus my nethunter is working well no problems,,,only problem is that to use bluetooth and wifi on it ?if u can help me with this i will be realy happy

S10 series's internal hardwares are not support for any kind of attack and we need to buy external adapters for it.

I built the kernel for my device, when I try to enable HID keyboard, the device just turns off. Maybe I need SELinux permissive.

I didn't tried external adapters because I don't have them..

Nethunter is lack of support in Samsung devices.

Also, S10 source is full of bugs. you can clone my S10+ source and make it nethunter support, then compile and using the kernel as a daily driver.

I felt a lag in nethunter kernel because nethunter is loading around 190 drivers to the kernel core.🥲

**Comment by qasimkhn** [comment]
> > > > > > dont u have nethunter kernel for s10 plus?
> > > > > 
> > > > > 
> > > > > I have a s10+ version.
> > > > 
> > > > 
> > > > i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature
> > > 
> > > 
> > > Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.
> > > I left the development, so I won't make any kernels :(
> > 
> > 
> > thanks alot brother,,, i am that good in it brother just still learning,,,any video tutorial u suggest please?and on samsung s10 plus my nethunter is working well no problems,,,only problem is that to use bluetooth and wifi on it ?if u can help me with this i will be realy happy
> 
> S10 series's internal hardwares are not supporter for any kind of attack. we need to buy external adapters for it.
> 
> I built the kernel for my device, when I try to enable HID keyboard, the device just turns off. Maybe I need SELinux permissive.
> 
> I didn't tried external adapters because I don't have them..
> 
> Nethunter is lack of support in Samsung devices.
> 
> Also, S10 source is full of bugs. you can clone my S10+ source and make it nethunter support, then compile and using the kernel as a daily driver.
> 
> I felt a lag in nethunter kernel because nethunter is loading around 190 drivers to the kernel core.🥲

thanks alot brother,,,,but there is no other way that on s10 plus i can just install some some little driver firmware via magisk modules  then nethunter can work with external adopters?because via kali nethunter lite installation on my s10 plus i can see nethunter working fine its just externel adopters left

**Comment by ravindu644** [comment]
> > > > > > > dont u have nethunter kernel for s10 plus?
> > > > > > 
> > > > > > 
> > > > > > I have a s10+ version.
> > > > > 
> > > > > 
> > > > > i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature
> > > > 
> > > > 
> > > > Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.
> > > > I left the development, so I won't make any kernels :(
> > > 
> > > 
> > > thanks alot brother,,, i am that good in it brother just still learning,,,any video tutorial u suggest please?and on samsung s10 plus my nethunter is working well no problems,,,only problem is that to use bluetooth and wifi on it ?if u can help me with this i will be realy happy
> > 
> > 
> > S10 series's internal hardwares are not supporter for any kind of attack. we need to buy external adapters for it.
> > I built the kernel for my device, when I try to enable HID keyboard, the device just turns off. Maybe I need SELinux permissive.
> > I didn't tried external adapters because I don't have them..
> > Nethunter is lack of support in Samsung devices.
> > Also, S10 source is full of bugs. you can clone my S10+ source and make it nethunter support, then compile and using the kernel as a daily driver.
> > I felt a lag in nethunter kernel because nethunter is loading around 190 drivers to the kernel core.🥲
> 
> thanks alot brother,,,,but there is no other way that on s10 plus i can just install some some little driver firmware via magisk modules then nethunter can work with external adopters?because via kali nethunter lite installation on my s10 plus i can see nethunter working fine its just externel adopters left

Yeah, I can give you the whole driver package as a magisk module. But they are not gonna load during the boot process, because we must enable a certain feature in the kernel core to load external kernel modules too.

**Comment by qasimkhn** [comment]
> > > > > > > > dont u have nethunter kernel for s10 plus?
> > > > > > > 
> > > > > > > 
> > > > > > > I have a s10+ version.
> > > > > > 
> > > > > > 
> > > > > > i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature
> > > > > 
> > > > > 
> > > > > Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.
> > > > > I left the development, so I won't make any kernels :(
> > > > 
> > > > 
> > > > thanks alot brother,,, i am that good in it brother just still learning,,,any video tutorial u suggest please?and on samsung s10 plus my nethunter is working well no problems,,,only problem is that to use bluetooth and wifi on it ?if u can help me with this i will be realy happy
> > > 
> > > 
> > > S10 series's internal hardwares are not supporter for any kind of attack. we need to buy external adapters for it.
> > > I built the kernel for my device, when I try to enable HID keyboard, the device just turns off. Maybe I need SELinux permissive.
> > > I didn't tried external adapters because I don't have them..
> > > Nethunter is lack of support in Samsung devices.
> > > Also, S10 source is full of bugs. you can clone my S10+ source and make it nethunter support, then compile and using the kernel as a daily driver.
> > > I felt a lag in nethunter kernel because nethunter is loading around 190 drivers to the kernel core.🥲
> > 
> > 
> > thanks alot brother,,,,but there is no other way that on s10 plus i can just install some some little driver firmware via magisk modules then nethunter can work with external adopters?because via kali nethunter lite installation on my s10 plus i can see nethunter working fine its just externel adopters left
> 
> Yeah, I can give you the whole driver package as a magisk module. But they are not gonna load during the boot process, because we must enable a certain feature in the kernel core to load external kernel modules too.

ok thanks brother ,,so what you suggest whats the best way to let it work?

**Comment by ravindu644** [comment]
> > > > > > > > > dont u have nethunter kernel for s10 plus?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I have a s10+ version.
> > > > > > > 
> > > > > > > 
> > > > > > > i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature
> > > > > > 
> > > > > > 
> > > > > > Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.
> > > > > > I left the development, so I won't make any kernels :(
> > > > > 
> > > > > 
> > > > > thanks alot brother,,, i am that good in it brother just still learning,,,any video tutorial u suggest please?and on samsung s10 plus my nethunter is working well no problems,,,only problem is that to use bluetooth and wifi on it ?if u can help me with this i will be realy happy
> > > > 
> > > > 
> > > > S10 series's internal hardwares are not supporter for any kind of attack. we need to buy external adapters for it.
> > > > I built the kernel for my device, when I try to enable HID keyboard, the device just turns off. Maybe I need SELinux permissive.
> > > > I didn't tried external adapters because I don't have them..
> > > > Nethunter is lack of support in Samsung devices.
> > > > Also, S10 source is full of bugs. you can clone my S10+ source and make it nethunter support, then compile and using the kernel as a daily driver.
> > > > I felt a lag in nethunter kernel because nethunter is loading around 190 drivers to the kernel core.🥲
> > > 
> > > 
> > > thanks alot brother,,,,but there is no other way that on s10 plus i can just install some some little driver firmware via magisk modules then nethunter can work with external adopters?because via kali nethunter lite installation on my s10 plus i can see nethunter working fine its just externel adopters left
> > 
> > 
> > Yeah, I can give you the whole driver package as a magisk module. But they are not gonna load during the boot process, because we must enable a certain feature in the kernel core to load external kernel modules too.
> 
> ok thanks brother ,,so what you suggest whats the best way to let it work?

I'll make a kernel when I'm free.

**Comment by ravindu644** [comment]
> > > > > > > > > dont u have nethunter kernel for s10 plus?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I have a s10+ version.
> > > > > > > 
> > > > > > > 
> > > > > > > i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature
> > > > > > 
> > > > > > 
> > > > > > Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.
> > > > > > I left the development, so I won't make any kernels :(
> > > > > 
> > > > > 
> > > > > thanks alot brother,,, i am that good in it brother just still learning,,,any video tutorial u suggest please?and on samsung s10 plus my nethunter is working well no problems,,,only problem is that to use bluetooth and wifi on it ?if u can help me with this i will be realy happy
> > > > 
> > > > 
> > > > S10 series's internal hardwares are not supporter for any kind of attack. we need to buy external adapters for it.
> > > > I built the kernel for my device, when I try to enable HID keyboard, the device just turns off. Maybe I need SELinux permissive.
> > > > I didn't tried external adapters because I don't have them..
> > > > Nethunter is lack of support in Samsung devices.
> > > > Also, S10 source is full of bugs. you can clone my S10+ source and make it nethunter support, then compile and using the kernel as a daily driver.
> > > > I felt a lag in nethunter kernel because nethunter is loading around 190 drivers to the kernel core.🥲
> > > 
> > > 
> > > thanks alot brother,,,,but there is no other way that on s10 plus i can just install some some little driver firmware via magisk modules then nethunter can work with external adopters?because via kali nethunter lite installation on my s10 plus i can see nethunter working fine its just externel adopters left
> > 
> > 
> > Yeah, I can give you the whole driver package as a magisk module. But they are not gonna load during the boot process, because we must enable a certain feature in the kernel core to load external kernel modules too.
> 
> ok thanks brother ,,so what you suggest whats the best way to let it work?

**I build it buddy :**

https://t.me/SamsungTweaks/211

**Comment by qasimkhn** [comment]
> > > > > > > > > > dont u have nethunter kernel for s10 plus?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I have a s10+ version.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > i also need s10+ G975f,,,i used the nethunter lite ARM64(FULL),,via magisk and its working but not all the features like external wifi etc supporting on nethunter lite,,,,can u please send it to me nethunter kernel for s10 plus so it can work with all nethunter feature
> > > > > > > 
> > > > > > > 
> > > > > > > Well, If you already know how to compile the kernel, you can refer this[ 7th guide of this repo](https://github.com/ravindu644/Simple-Android-Guides#%EF%B8%8F-quick-links-) to make the nethunter kernel.
> > > > > > > I left the development, so I won't make any kernels :(
> > > > > > 
> > > > > > 
> > > > > > thanks alot brother,,, i am that good in it brother just still learning,,,any video tutorial u suggest please?and on samsung s10 plus my nethunter is working well no problems,,,only problem is that to use bluetooth and wifi on it ?if u can help me with this i will be realy happy
> > > > > 
> > > > > 
> > > > > S10 series's internal hardwares are not supporter for any kind of attack. we need to buy external adapters for it.
> > > > > I built the kernel for my device, when I try to enable HID keyboard, the device just turns off. Maybe I need SELinux permissive.
> > > > > I didn't tried external adapters because I don't have them..
> > > > > Nethunter is lack of support in Samsung devices.
> > > > > Also, S10 source is full of bugs. you can clone my S10+ source and make it nethunter support, then compile and using the kernel as a daily driver.
> > > > > I felt a lag in nethunter kernel because nethunter is loading around 190 drivers to the kernel core.🥲
> > > > 
> > > > 
> > > > thanks alot brother,,,,but there is no other way that on s10 plus i can just install some some little driver firmware via magisk modules then nethunter can work with external adopters?because via kali nethunter lite installation on my s10 plus i can see nethunter working fine its just externel adopters left
> > > 
> > > 
> > > Yeah, I can give you the whole driver package as a magisk module. But they are not gonna load during the boot process, because we must enable a certain feature in the kernel core to load external kernel modules too.
> > 
> > 
> > ok thanks brother ,,so what you suggest whats the best way to let it work?
> 
> **I build it buddy :**
> 
> https://t.me/SamsungTweaks/211

oh thanks alot brother,,,if i install this then u think i will be able to use external wifi and usb adopters ?
